"""add ai_quality_score to book_condition_scans

Revision ID: c10d8dce56c4
Revises: 5e98ee344f78
Create Date: 2026-05-13 10:51:18.006377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c10d8dce56c4'
down_revision: Union[str, None] = '5e98ee344f78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('unique_grade_subject', table_name='grade_subjects')
    op.drop_table('grade_subjects')
    op.create_foreign_key(None, 'book_allocations', 'learners', ['learner_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'book_allocations', 'book_copies', ['book_copy_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'book_boxes', 'deliveries', ['delivery_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'book_boxes', 'books', ['book_id'], ['id'], ondelete='RESTRICT')
    op.add_column('book_condition_scans', sa.Column('ai_quality_score', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'book_condition_scans', 'book_copies', ['book_copy_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'book_condition_scans', 'ai_model_versions', ['ai_model_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'book_copies', 'books', ['book_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'book_copies', 'schools', ['school_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'book_requests', 'books', ['book_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'book_requests', 'schools', ['school_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'books', 'grade_levels', ['grade_level_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'books', 'subjects', ['subject_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'damage_notifications', 'users', ['reported_by'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'damage_notifications', 'book_copies', ['book_copy_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'deliveries', 'book_requests', ['book_request_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'escalations', 'replacement_requests', ['replacement_request_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'grades', 'schools', ['school_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'learners', 'grades', ['grade_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'parent_acknowledgements', 'book_allocations', ['allocation_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'parent_acknowledgements', 'users', ['parent_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'parent_learners', 'learners', ['learner_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'parent_learners', 'users', ['parent_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'replacement_requests', 'damage_notifications', ['damage_notification_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'school_books_inventory', 'schools', ['school_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'school_books_inventory', 'books', ['book_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'schools', 'departments', ['department_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'user_roles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'users', 'schools', ['school_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'users', 'departments', ['department_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    op.drop_constraint(None, 'schools', type_='foreignkey')
    op.drop_constraint(None, 'school_books_inventory', type_='foreignkey')
    op.drop_constraint(None, 'school_books_inventory', type_='foreignkey')
    op.drop_constraint(None, 'replacement_requests', type_='foreignkey')
    op.drop_constraint(None, 'parent_learners', type_='foreignkey')
    op.drop_constraint(None, 'parent_learners', type_='foreignkey')
    op.drop_constraint(None, 'parent_acknowledgements', type_='foreignkey')
    op.drop_constraint(None, 'parent_acknowledgements', type_='foreignkey')
    op.drop_constraint(None, 'learners', type_='foreignkey')
    op.drop_constraint(None, 'grades', type_='foreignkey')
    op.drop_constraint(None, 'escalations', type_='foreignkey')
    op.drop_constraint(None, 'deliveries', type_='foreignkey')
    op.drop_constraint(None, 'damage_notifications', type_='foreignkey')
    op.drop_constraint(None, 'damage_notifications', type_='foreignkey')
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_constraint(None, 'book_requests', type_='foreignkey')
    op.drop_constraint(None, 'book_requests', type_='foreignkey')
    op.drop_constraint(None, 'book_copies', type_='foreignkey')
    op.drop_constraint(None, 'book_copies', type_='foreignkey')
    op.drop_constraint(None, 'book_condition_scans', type_='foreignkey')
    op.drop_constraint(None, 'book_condition_scans', type_='foreignkey')
    op.drop_column('book_condition_scans', 'ai_quality_score')
    op.drop_constraint(None, 'book_boxes', type_='foreignkey')
    op.drop_constraint(None, 'book_boxes', type_='foreignkey')
    op.drop_constraint(None, 'book_allocations', type_='foreignkey')
    op.drop_constraint(None, 'book_allocations', type_='foreignkey')
    op.create_table('grade_subjects',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('grade_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('subject_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('school_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='MyISAM'
    )
    op.create_index('unique_grade_subject', 'grade_subjects', ['grade_id', 'subject_id'], unique=False)
    # ### end Alembic commands ###
